cc_test(
    name = "test",
    srcs = ["test.cc"],
    deps = [
        "@com_google_googletest//:gtest_main",
        "@com_google_absl//absl/strings",
        "//bitcoin",
        "//util",
        "//net"
    ],
)
